name: Run small script (Ruby)

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 13 * * *"  # daily at 13:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      MY_API_KEY: ${{ secrets.MY_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"  # or 3.2, whatever you like

      - name: Run Ruby script
        run: ruby my_job.rb
